src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * @ORM\Entity(repositoryClass=CommentaireRepository::class)
 */
class Commentaire
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=256)
     */
    private $titre;


    /**
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="commentaires")
     */
    private $email;

    public function __construct()
    {
        $this->created_at = new \Datetime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getEmail(): ?User
    {
        return $this->email;
    }

    public function setEmail(?User $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    
 
}

src/Form/CommentaireType.php
<?php

namespace App\Form;

use App\Entity\Commentaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommentaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
           
            ->add('titre')
            ->add('message')
            
            
           
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Commentaire::class,
        ]);
    }
}

src/Controller/CommentaireController.php
<?php

namespace App\Controller;

use App\Entity\Commentaire;
use App\Form\CommentaireType;
use App\Repository\CommentaireRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


/**
 * @Route("/commentaire")
 */
class CommentaireController extends AbstractController
{
    /**
     * @Route("/", name="commentaire_index", methods={"GET","POST"})
     */
    public function index(CommentaireRepository $commentaireRepository, Request $request): Response
    {
        $commentaire = new Commentaire();
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            $commentaire->setEmail($this->getUser());
            
            $entityManager->persist($commentaire);
            $entityManager->flush();

            return $this->redirectToRoute('commentaire_index');
        }
        return $this->render('commentaire/index.html.twig', [
            'commentaire' => $commentaire,
            'form' => $form->createView(),
            'commentaires' => $commentaireRepository->findAll(),
        ]);
    }

    
    /**
     * @Route("/{id}", name="commentaire_show", methods={"GET"})
     */
    public function show(Commentaire $commentaire): Response
    {
        return $this->render('commentaire/show.html.twig', [
            'commentaire' => $commentaire,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="commentaire_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Commentaire $commentaire): Response
    {
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('commentaire_index');
        }

        return $this->render('commentaire/edit.html.twig', [
            'commentaire' => $commentaire,
            'form' => $form->createView(),

        ]);

    }

    /**
     * @Route("/{id}", name="commentaire_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Commentaire $commentaire): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commentaire->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($commentaire);
            $entityManager->flush();
        }

        return $this->redirectToRoute('commentaire_index');
    }
   


    
}

templates/commentaire/_delete_form.html.twig
<form method="post" action="{{ path('commentaire_delete', {'id': commentaire.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commentaire.id) }}">
    <button class="btn">Delete</button>
</form>

templates/commentaire/_form.html.twig
<div class="container">
{{ form_start(form) }}

    {{ form_widget(form) }}
    <ul class="list-inline social-buttons">
    <li>
    <button class="btn btn-danger">{{ button_label|default('Envoyer') }}</button>
    </li>
    </ul>
{{ form_end(form) }}
</div>

templates/commentaire/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Commentaire{% endblock %}

{% block body %}
    <h1>Edit Commentaire</h1>

    {{ include('commentaire/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('commentaire_index') }}">back to list</a>

    {{ include('commentaire/_delete_form.html.twig') }}
{% endblock %}

templates/commentaire/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livre d'or - Domi'Licious{% endblock %}
{% block body %}

<div id="page-content" class="archives-page">
	<div class="container">
		<div class="row">
             <div id="main-content" class="col-md-10">
				<article class="contact">
					<div class="art-header">
                        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                        {{ form_start(form) }}
                         {{ form_row(form) }}
                            <button class="btn btn-danger">{{ button_label|default('Envoyer') }}</button>
                        {{ form_end(form) }}
                
                        {% endif %}   
                </div>
                </article>
            </div>
        </div>
    </div>                 
</div>

    <div class="container">

                <div class="col-md-10">       <!-- Standard button -->
                    <button type="button" class="btn btn-danger ribbon"><h5 id="bandeau">Commentaires utilisateurs</h5></button>
                </div>
            
    </div>
 <div id="page-content" class="archives-page">
		<div class="container">
			<div class="row">
                <div id="main-content" class="col-md-10">
					<article class="contact">
						<div class="art-header">
                                 {% for commentaire in commentaires %}
                                <h6>{{ commentaire.email }}</h6>
                                    <div class="col-md-12">
                                         <div class="row">
                                            <p><em>{{ commentaire.titre }}</em></p>
                                            <p><em>{{ commentaire.message }}</em></p>
                                            <p><em>{{ commentaire.createdAt ? commentaire.createdAt|date('d-m-Y') : '' }}</em></p>
                                         </div>
                                    </div>
                                {% endfor %}
                        </div>
                    </article>
                </div>
            </div>          
     </div>           
</div>


          
{% endblock %}

templates/commentaire/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Commentaire{% endblock %}

{% block body %}
    <h1>Create new Commentaire</h1>

    {{ include('commentaire/_form.html.twig') }}

    <a href="{{ path('commentaire_index') }}">back to list</a>
{% endblock %}

templates/commentaire/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commentaire{% endblock %}

{% block body %}
    <h1>Commentaire</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ commentaire.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ commentaire.titre }}</td>
            </tr>
            <tr>
                <th>Message</th>
                <td>{{ commentaire.message }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ commentaire.createdAt ? commentaire.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('commentaire_index') }}">back to list</a>

    <a href="{{ path('commentaire_edit', {'id': commentaire.id}) }}">edit</a>

    {{ include('commentaire/_delete_form.html.twig') }}
{% endblock %}